# Generated by Django 5.2.1 on 2025-05-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='join_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
