# Generated by Django 5.2.1 on 2025-05-26 15:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_plant',
            new_name='Plants_assigned_to_user',
        ),
        migrations.AlterField(
            model_name='hops_species',
            name='also_known_as',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
