# Generated by Django 5.2.1 on 2025-05-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hops', '0002_rename_user_plant_plants_assigned_to_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hops_species',
            name='beer_style_guide',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hops_species',
            name='origin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='hops_species',
            name='primary_use',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
