# Generated by Django 5.2.1 on 2025-05-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hops', '0003_alter_hops_species_beer_style_guide_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasting_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavour', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hops_species',
            name='flavour',
        ),
        migrations.AlterField(
            model_name='plants_assigned_to_user',
            name='date_planted',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='hops_species',
            name='flavor',
            field=models.ManyToManyField(blank=True, related_name='hops_varieties', to='hops.tasting_notes'),
        ),
    ]
