# Generated by Django 5.2.1 on 2025-05-27 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hops', '0004_tasting_notes_remove_hops_species_flavour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasting_notes',
            old_name='flavour',
            new_name='flavor',
        ),
    ]
