# Generated by Django 5.2.1 on 2025-05-27 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hops', '0005_rename_flavour_tasting_notes_flavor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasting_notes',
            old_name='flavor',
            new_name='name',
        ),
    ]
